Files:
  frames_radar_data: ./data/radcam_log.json
  radar_data_file: ./data/Control_test1.json
  video_file: ./data/Controlled_test.avi

FrameModeDefaults:
  TrackbarDefaults:
    slider_xoffset: 219
    slider_yoffset: 119
    xy_trackbar_scale: 0.71
  rad_cam_offset: 0
  scalemm2px: 0.5
  wait_ms: 33
  playback_fps: 1

SensorAngles:
  alpha: 47.5
  beta: 17.5
SensorOffsets:
  offsetx: 325
  offsety: 595
  offsetz: 850
VideoModeDefaults:
  TrackbarDefaults:
    slider_xoffset: 167
    slider_yoffset: 140
    xy_trackbar_scale: 0.5
  rad_cam_offset: 1500
  scalemm2px: 0.5
  wait_ms: 33
  playback_fps: 27
remove_noise: False