rad_cam_offset: 2300 # ms, positive if radar is ahead of video
scalemm2px: 0.5 
wait_ms: 33 # wait time between frames in ms

TrackbarDefaults:
  slider_xoffset: 0
  slider_yoffset: 0
  xy_trackbar_scale: 1 
