Files:
  radar_data_file: './data/Control_test1.json'
  video_file: './data/Controlled_test.avi'
  
TrackbarDefaults:
  slider_xoffset: 167
  slider_yoffset: 140
  xy_trackbar_scale: 0.5

rad_cam_offset: 2300
scalemm2px: 0.5
wait_ms: 33
